title: Nadiia Gorash # your name (or website title) here
logo: "/images/logo_1.png?" # raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist
  <br><br>
  GIS
  <br><br>
  <a href="https://www.linkedin.com/in/nadiiagorash/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
